In [1]:
print ('SAHE')


SAHE


In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [4]:
np.abs


<ufunc 'absolute'>

In [6]:

data = np.array([1, 5, 3, 9, 2])

print("Maximum Value:", np.max(data))
print("Minimum Value:", np.min(data))
print("Sum of Elements:", np.sum(data))
print("Average (Mean):", np.mean(data))
print("Standard Deviation:", np.std(data))

Maximum Value: 9
Minimum Value: 1
Sum of Elements: 20
Average (Mean): 4.0
Standard Deviation: 2.8284271247461903
